CREATE DATABASE security_testing;
USE security_testing;

CREATE TABLE Credentials (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE Credentials
CHANGE username email VARCHAR(255) NOT NULL UNIQUE;
